### PR TITLE
Added namespace functionality

### PR DESCRIPTION
**Pull request by BiscuiTech**
This essentially adapts the hoc with a second variable being the namespace. This variable is then forwarded to the Context and used by the hook for the api request. At the api layer, the namespace is used to dynamically fetch the strings. 

Please review the two TODOs in LocaleContext.ts. I'm not totally familiar with TypeScrypt. And also any changes you would like to make! Thanks.

### CODE REVIEW

**Comment by fwojciec** [comment]
Thanks!  I'm going to have a closer look tomorrow, but on the first glance this looks good!

**Comment by BiscuiTech** [comment]
I just had a realization: common is not actually _common_ in this example. 

Maybe we could pass a common package inside the requested package on the api layer. Like so:

```typescript
import { NextApiRequest, NextApiResponse } from 'next'
import locales from '../../../translations/locales'
import { isLocale, Translations } from '../../../translations/types'

export default (req: NextApiRequest, res: NextApiResponse<Translations>) => {
  const { query: { lang } } = req
  const { namespace }: any = req.query
  if (typeof lang !== 'string' || !isLocale(lang)) {
    res.status(400).json({ error: 'error: unknown locale' })
  } else {
    const locale: any = locales[lang];
    const strings: any = locale[namespace];

   // Get common strings first and insert in the localized package
    const { common }= locales[lang];
    const payload = {  ...common, strings }
    res.status(200).json(payload)
  }
}
```

What do you think?

**Comment by fwojciec** [comment]
@BiscuiTech Apologies for not getting back to you yet -- things have been more busy than I had anticipated.  I should have some time to work on this later this week.

**Comment by BiscuiTech** [comment]
No worries, I worked on implementing this on my [own website](https://github.com/BiscuiTech/BiscuiT). I really liked having a `translations["common"]` object with common ui translations - like button text, navbar, etc. So I added the common object to every response at the API level. I personally find it useful, but feel free to remove it in favor in another paradigm. 

With this latest commit, I am happy where I landed.

**Comment by fwojciec** [comment]
Thanks so much for the PR and sorry it took so long to merge it!

**Pull request merged**
